baseURL = "http://brabemi.github.io/"
languageCode = "en-us"
title = "Mirek's blog"
theme = "ink"

[params]
    subtitle = "Mirek's personal blog"

    # Optional 64x64 avatar image.
    avatar = "https://www.gravatar.com/avatar/457c56f5368e2bd333e3977494efc39a.jpg?s=64"

    # Content types to disable Disqus on.
    disableDisqusTypes = ["page"]

    featherIconsCDN = true

    mode = "auto" # "dark" or "auto"
    # customCSS = "css/custom.css"  # Custom CSS applied to default styles.
    # customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
    # customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/brabemi"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
